GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Test title",
  "author": "Test author",
  "url": "www.test-url.com",
  "likes": 50
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Another title",
  "author": "Yet another author",
  "url": "www.test-url-something.com",
  "likes": 1234
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "A blog title",
  "author": "An author",
  "url": "www.test-url-something-else.com",
  "likes": 100,
  "user": "607002d3f85a421418756daa"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYxNzk2OTI2MH0.TLWNOC20rzVEfCc7JY1OQcwILUtYgXcH1Wem-yDc0Ic

{
  "title": "Syed's blog",
  "author": "Authorised author",
  "url": "www.test-url-something-else.com",
  "likes": 42,
  "user": "607002d3f85a421418756daa"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGgfhgOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYxNzk3NDExM30.2UAL5-Pok163hHHEDvj_IO9Uj9Y4_RBr_RuMa3rwJe8

{
  "title": "This should not work",
  "author": "Unauthorised author",
  "url": "www.test-url-something-else.com",
  "likes": 100,
  "user": "607002d3f85a421418756daa"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpoZW5kcml4IiwiaWQiOiI2MDcwMTc4ZjEyYjI5ZjIxYjRiMmM4MGQiLCJpYXQiOjE2MTgwNTQxODJ9.Fi_nsgVuwGgXMp0swInC20uf_tzjp7IIPFufuhRjLNI

{
  "title": "Blog request without userId",
  "author": "Author userId",
  "url": "www.test-url-something-else.com",
  "likes": 666
}

###
DELETE http://localhost:3003/api/blogs/60718c5cb071300da89f3417 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpoZW5kcml4IiwiaWQiOiI2MDcwMTc4ZjEyYjI5ZjIxYjRiMmM4MGQiLCJpYXQiOjE2MTgwNTQxODJ9.Fi_nsgVuwGgXMp0swInC20uf_tzjp7IIPFufuhRjLNI

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYyMDAzOTE2NX0.w8U56_HBAG9kb0gJVUrdrOC3xZwVlUIueyKNT2VV2xM

{
  "title": "Test",
  "author": "author",
  "url": "www.test-url-something-else.com",
  "likes": 42,
  "user": "607002d3f85a421418756daa"
}

###
POST http://localhost:3003/api/blogs/608fd62743af8212007dc961/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYyMDAzOTE2NX0.w8U56_HBAG9kb0gJVUrdrOC3xZwVlUIueyKNT2VV2xM

{
  "comment": "Test comment 2"
}

###
POST http://localhost:3003/api/blogs/608e585e9cc2e92a348d9278/comments
Content-Type: application/json

{
  "comment": "Mans got that crpyto Lambo"
}