GET http://localhost:3003/api/blogs HTTP/1.1

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Test title",
  "author": "Test author",
  "url": "www.test-url.com",
  "likes": 50
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Another title",
  "author": "Yet another author",
  "url": "www.test-url-something.com",
  "likes": 1234
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "A blog title",
  "author": "An author",
  "url": "www.test-url-something-else.com",
  "likes": 100,
  "user": "607002d3f85a421418756daa"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYxNzk2OTI2MH0.TLWNOC20rzVEfCc7JY1OQcwILUtYgXcH1Wem-yDc0Ic

{
  "title": "Syed's blog",
  "author": "Authorised author",
  "url": "www.test-url-something-else.com",
  "likes": 42,
  "user": "607002d3f85a421418756daa"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGgfhgOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYxNzk3NDExM30.2UAL5-Pok163hHHEDvj_IO9Uj9Y4_RBr_RuMa3rwJe8

{
  "title": "This should not work",
  "author": "Unauthorised author",
  "url": "www.test-url-something-else.com",
  "likes": 100,
  "user": "607002d3f85a421418756daa"
}

###
DELETE http://localhost:3003/api/blogs/6070549934c7a72b98bd3aa9 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWlkZXIiLCJpZCI6IjYwNzAwMmQzZjg1YTQyMTQxODc1NmRhYSIsImlhdCI6MTYxNzk2OTI2MH0.TLWNOC20rzVEfCc7JY1OQcwILUtYgXcH1Wem-yDc0Ic
